name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run Tests
      run: |
        cd .github/
        docker-compose run lms /openedx/requirements/eol_jump_to/.github/test.sh
